fix build with gcc 4.8
Fx the following build failures with gcc 4.8 raised since version 0.9.4
and
https://github.com/uoaerg/wavemon/commit/674efd8297997d63481705ece71b83cb19eb3d15
and
https://github.com/uoaerg/wavemon/commit/220163d9c8763471edfb528459c788aee07df81d:

wavemon.h: In function 'argv_find':
wavemon.h:311:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (size_t i = 0; argv[i]; i++)
  ^

about_scr.c: In function 'scr_about_init':
about_scr.c:40:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (size_t i = 0; i < ARRAY_SIZE(about_lines); i++) {
  ^
about_scr.c:42:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (size_t j = 0; j < strlen(about_lines[i]); j++)
   ^

Fixes:
 - http://autobuild.buildroot.org/results/a6ee162cf04b70b144b54e1ca4b7b2421071c50c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>