Fix musl build
Add missing header `stdint.h` to fix build with the musl C library:

```
wavemon.h:240:7: error: unknown type name ‘int8_t’
```